//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicines
    {
        public long id_medicine { get; set; }
        public long pharmacy { get; set; }
        public string name_medicine { get; set; }
        public string symptoms { get; set; }
        public Nullable<long> count { get; set; }
        public long price { get; set; }
    
        public virtual pharmacy_list pharmacy_list { get; set; }
    }
}
